#!/bin/bash

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

feh --no-fehbg -z --bg-scale ~/Pictures/favwallpaper/*

greenclip daemon &

~/.config/polybar/launch.sh &

nm-applet &

killall sxhkd
sxhkd &
picom &
killall dunst
dunst &
bash ~/.config/i3/scripts/scroll.sh &

xss-lock --transfer-sleep-lock -- ~/.config/i3/scripts/lock.sh --nofork &

bspc monitor -d 1 2 3 &
bspc config window_gap 0
bspc config border_width 0
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
