#!/bin/bash

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

feh --no-fehbg -z --bg-scale ~/Pictures/favwallpaper/*

killall greenclip
greenclip daemon &

~/.config/polybar/launch.sh

killall nm-applet
nm-applet &

killall sxhkd
sxhkd &
picom &
killall dunst
dunst &
bash ~/.config/i3/scripts/scroll.sh &

killall xss-lock
xss-lock --transfer-sleep-lock -- ~/.config/i3/scripts/lock.sh --nofork &

xsetroot -cursor_name left_ptr

bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc monitor -d 1 2 3 4
bspc config window_gap 0
bspc config border_width 0
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a Brave-browser desktop='^1' follow=on
