[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1b1b1b"
foreground = "#ebdbb2"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[font]
size = 12

[font.normal]
family = "JetbrainsMono Nerd Font"
[scrolling]
history = 2000
[window]
opacity = 0.8

[window.dimensions]
columns = 120
lines = 40
